= GraphQL Playground Library

Library encapsulating GraphQL Playground, a GraphQL IDE for better development workflows.

== Compatibility

[cols="1,1,3", options="header"]
|===
|Version
|Min. XP Version
|Dependency

|0.0.2
|7.0.0
|com.enonic.lib:lib-graphql-playground:0.0.2
|0.0.1
|7.0.0
|com.enonic.lib:lib-graphql-playground:0.0.1
|===

== Build

To build this project, execute the following:

[source,bash]
----
./gradlew clean build
----

== Usage

==== Step 1: Include the library

* Check that the Enonic repository is in the list of repositories

[source,gradle]
----
repositories {
  maven {
    url 'https://repo.enonic.com/public'
  }
}
----

* Add the following dependency (where `<version>` is the actual version to use):

[source,gradle]
----
dependencies {
  include 'com.enonic.lib:lib-graphql-playground:<version>'
}
----


==== Step 2: Handle GET requests of your GraphQL endpoint


* We suppose that you already have a service or webapp endpoint serving as your GraphQL endpoint and handling POST requests

./services/graphql/graphql.js
[source,javascript]
----
var guillotineLib = require('/lib/guillotine');
var graphQlLib = require('/lib/graphql');

var schema = guillotineLib.createSchema();

exports.post = function (req) {
  var body = JSON.parse(req.body);
  var result = graphQlLib.execute(schema, body.query, body.variables);
  return {
    contentType: 'application/json',
    body: result
  };
};
----


* Add the following to this controller to handle GET requests and render the GraphQL Playground IDE

./services/graphql/graphql.js
[source,javascript]
----
var graphqlPlaygroundLib = require('/lib/graphql-playground');

exports.get = function (req) {
  var body = graphqlPlaygroundLib.render();
  return {
    contentType: 'text/html',
    body: body
  };
};
----
